services:
  - type: worker
    name: upi-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
