services:
  - type: worker
    name: upi-bot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y python3.11 python3.11-venv python3.11-dev
      python3.11 -m venv venv
      . venv/bin/activate
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: venv/bin/python main_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
